version: '3.9'

services:
  backend:
    build: ./backend
    container_name: music-backend
    ports:
      - "1337:1337"
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    container_name: music-frontend
    ports:
      - "3000:80"
    